name: Smoke test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install build-essential software-properties-common
        sudo add-apt-repository ppa:kelleyk/emacs && sudo apt update && sudo apt install emacs26
        export HOME=$PWD/..
        mkdir ../.emacs.d && cp -R ./* ../.emacs.d
    - name: Run emacs
      run: |
        emacs -nw --batch --eval '(let ((debug-on-error t)
                              (url-show-status nil)
                              (user-emacs-directory default-directory)
                              (user-init-file (expand-file-name "init.el"))
                              (load-path (delq default-directory load-path)))
                           (load-file user-init-file)
                           (run-hooks (quote after-init-hook)))'
